### ISSUE TITLE
Build Fail for Octicon Icon

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#14]
In my most recent merge I received an email with this: 

> The tag `octicon` on line 12 in `/_layouts/app.html` is not a recognized Liquid tag. 

I'm not totally sure why this is, given all the octicons worked locally for me fine. Maybe it's something to do with intern privileges not allowing me to access octicons?

cc/ @bkeepers @benbalter @parkr because pages things :)

**Comment by bkeepers** [comment]
I pushed https://github.com/probot/probot.github.io/commit/d24d37325c223fc2e5cba786f6ec986129a20fc3 and the build succeeded. Definitely looks like an employee permission thing.

**Comment by benbalter** [comment]
GitHub Octicons is currently only available to staff. We could either make it available to everyone (not 100% sure the use case makes sense to support), or figure out how to whitelist this repo/@hiimbex.

**Comment by bkeepers** [comment]
> (not 100% sure the use case makes sense to support)

Since octicons are open source and anyone can use them, I'm curious, why wouldn't it make sense to support them on GitHub Pages?

Either way, I'll close this out since there's nothing we need to do in this repo. I'll just merge PRs here for now.
