### ISSUE TITLE
Add section for "Getting started with JavaScript"

### ISSUE THREAD

**Issue by tcbyrd** [probot/probot.github.io#144]
From https://github.com/probot/friction/issues/23

> JavaScript is one point of friction that I've heard people often cite in getting started with Probot. I’d love to include some links for quickly getting up to speed on JavaScript in the Probot docs.

It can be tricky for newcomers to learn Probot if they aren't comfortable with JavaScript, and since it depends heavily on server-to-server communication and event emitters, the more popular tutorials on learning JavaScript don't cover some of the techniques we use. Several links are posted in the issue referenced in `/friction`. We should make a section in the Probot documentation that covers some of the concepts of JavaScript that are important to understanding how you should architect a Probot application.

Marking this as a `help wanted` since I think this would be a great issue for someone from the community to help contribute. Maybe we create an article similar to Facebook's "[Thinking in React](https://reactjs.org/docs/thinking-in-react.html)" where we talk about "Thinking with Events"?

**Comment by kindacoder** [comment]
@tcbyrd , As a beginner I faced difficulty to grasp the concept of webhook. Can I make an easy tutorial on that?

**Comment by tcbyrd** [comment]
@kindacoder Definitely feel free to write something up. I could see something structured similar to this GitHub article on [Building a CI Server](https://developer.github.com/v3/guides/building-a-ci-server/), but geared towards Javascript/Express instead of Ruby/Sinatra. We already have a section on how [Probot handles Webhooks](https://probot.github.io/docs/webhooks/), but if there was a more general article outside of Probot on Webhooks, I could see linking to that from the Probot docs.
