### ISSUE TITLE
Make it easier to find apps on the featured apps page

### ISSUE THREAD

**Issue by tcbyrd** [probot/probot.github.io#145]
As we get more Apps on the site, it is becoming a bit more difficult to find an app you want to use. We could add better search and categorization to https://probot.github.io/apps/, but I also feel this will just end up looking like `/marketplace`. Maybe the end goal is for the Apps link to just take you to something like `https://github.com/marketplace/category/probot`?

@bkeepers Curious where you see that going. We could build a really simple search pretty quickly that just filters based on the descriptions we already have on the page, but we don't have any categorization setup for Probot Apps. That could be an interesting exercise to help us better categorize Probot Apps, but also has potential for massive 🚲 bike 🏚 shedding.

----
Ref: https://github.com/probot/friction/issues/27

**Comment by kindacoder** [comment]
@tcbyrd I can add filter based search on the page. Should i work on this issue??

**Comment by hiimbex** [comment]
cc/ https://github.com/probot/probot.github.io/pull/18 from way back when with some category ideas for probot
