### ISSUE TITLE
Mailchimp redirect goes to https://opensoul.org

### ISSUE THREAD

**Issue by RichardLitt** [probot/probot.github.io#149]
The newsletter signup on the website redirects to https://opensoul.org/ on completion. It should probably redirect to https://probot.github.io/.

**Comment by bkeepers** [comment]
Then how would you suggest I drive traffic to my unmaintained blog?

Jk, good catch. Investigating how to fix that now.

**Comment by bkeepers** [comment]
Fixed. Thanks!

**Comment by RichardLitt** [comment]
:D
