### ISSUE TITLE
deep linking on doc headings

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#15]
The anchors are already added (for example: [/docs/development/#configure-a-github-app](https://probot.github.io/docs/development/#configure-a-github-app)),  It just needs the little link icon that shows up on hover.

I know we've done this with a JavaScript plugin in the past, but it'd be awesome if this just worked when using primer. The styles are all there, and I've tested that it works fine when crafting the markup below. All that's needed is to inject the `<a class="anchor">…octicon…</a>` bit.

@benbalter Know of any neat tricks to do this?

```
<div class="markdown-body">
  <h1>
    <a id="foobar" class="anchor" href="#foobar" aria-hidden="true">
      {% octicon link height:16 }
    </a>
    Foobar
  </h1>
</div>
```

**Comment by benbalter** [comment]
I've used AnchorJS in the past, I don't know of a way to get Kramdown to add the additional markup (although I'd be glad to support a plugin if it doesn't add too much complexity/overhead).
