### ISSUE TITLE
Add FAQ section to the docs

### ISSUE THREAD

**Issue by itaditya** [probot/probot.github.io#158]
Many people have been asking various questions regarding usage of probot. 

A question like 
>how do we install probot in github enterprise ? (https://github.com/probot/probot/issues/500)

must be answered somewhere. I think an FAQ section would be the best thing to cover these questions. I would like to work on making the FAQ section. @gr2m /cc @bkeepers @JasonEtco what are your thoughts ?

**Comment by JasonEtco** [comment]
This is a great idea. Perhaps dig through the [`probot/friction`](https://github.com/probot/friction) repo to see what are some of the common questions people have.

**Comment by itaditya** [comment]
I'll start working on this right away. Also I have opened an issue in `probot/friction` for the github enterprise question. Should I comment the solution there also ?

**Comment by JasonEtco** [comment]
>  Should I comment the solution there also ?

Sure 👍

**Comment by itaditya** [comment]
I will be listing all the FAQ questions here. Suggestions are welcome.

**Comment by JasonEtco** [comment]
Some initial thoughts to get the ball rolling:

> How can my app receive webhooks?

> Does this Probot App work on GitHub Enterprise?

> How can I deploy my app?

**Comment by aps120797** [comment]
Some more FAQs:
> Is Probot a product of GitHub?
> What are some suggested platforms where I can deploy my GitHub application?
> Where can I ask problem I am facing while developing Probot app? 
(Answer to this could be Slack community of Probot and Stackoverflow questions tagged with `probot` tag)
Will be adding more questions on the same. 😄

**Comment by itaditya** [comment]
> Where can I ask problem I am facing while developing Probot app?
(Answer to this could be Slack community of Probot and Stackoverflow questions tagged with probot tag)

and the `probot/friction` repo I guess

**Comment by itaditya** [comment]
> Where can I get the list of all supported webhook `{event}.{action}` ?

> Can I use typescript while building probot app ?

> How can I see if my bot is working without actually performing the action on Github which triggers the webhook ?

**Comment by itaditya** [comment]
@aps120797 yes you are right, let's first list down all the FAQs and then we can discuss the appropriate answers :smile:

**Comment by aps120797** [comment]
> How can I expose my localhost to the internet to receive webhook payloads?
> What are some common probot extensions that we can use?

**Comment by itaditya** [comment]
> How to make a github app which needs to do many things ?

**Comment by bkeepers** [comment]
In general, if we're getting the same question repeatedly, then I think we should attempt to improve the documentation related to that question before adding it to an FAQ. Only after we've done everything we can and are still getting the same question do I think it should be added to an FAQ.

**Comment by itaditya** [comment]
@bkeepers how about putting up an FAQ section and see the analytics for all questions. Then give higher priority to improving the docs of the most viewed question. 
This will have two advantages. 
1. We can check which areas in docs needs the most refinement.
1. Users won't have to wait till we perfect the docs.

**Comment by hiimbex** [comment]
@itaditya if I'm being honest, I'm not sure we get enough traffic for any useful analytics. I think anything we would put in an FAQ should just direct users to docs where these questions are answered.

**Comment by itaditya** [comment]
> direct users to docs where these questions are answered
 @hiimbex this sounds good too. @JasonEtco what are your thoughts on this ?

**Comment by hiimbex** [comment]
We have no current plans to make an FAQ session.
