### ISSUE TITLE
Implement caching by use of Service Workers 

### ISSUE THREAD

**Issue by knrt10** [probot/probot.github.io#159]
Internet connection can be a problem many times and use of **Service Workers** will help user's to use probot's site without any interruption of their internet connection.

I would like to work on this issue.@bkeepers /cc @JasonEtco @tcbyrd @gr2m what are your thoughts on this?

**Comment by itaditya** [comment]
As we can simulate webhooks locally we don't even need internet while development. The ability to read docs offline, would be like a cherry on top :smile: . @knrt10 :+1:

**Comment by knrt10** [comment]
Its not only for developers of probot but also for a user who visits the page with slow internet connection.

**Comment by bkeepers** [comment]
I get that this is a pain point, but considering Probot apps need to be online to interact with GitHub, it feels like this would have a limited impact.

Can you point to some examples of what it would take to make the docs available offline? I saw the [discussion in chat](https://probot-talk.slack.com/archives/C6S4FC8AF/p1523714450000044) that this would require rewriting the docs site as a SPA, which I'm not in favor of.

**Comment by itaditya** [comment]
One other thing, as it is a completely static site browsers have pretty decent caching available by default.

**Comment by itaditya** [comment]
@bkeepers according to google, for building PWAs, using the App Shell model is the best approach, since we can cache static content like css, and basic html layout (which is common to all pages for a site) and after that we request the dynamic parts (mainly data) which may change from page to page. Refer [this](https://developers.google.com/web/fundamentals/architecture/app-shell) for more detail on App Shell

**Comment by itaditya** [comment]
https://developers.google.com/web/updates/images/2015/11/appshell/appshell-1.jpg

**Comment by aps120797** [comment]
PWABuilder is a great and simple tool to convert applications into PWA.
 It currently offers 4 different types of service workers depending on one needs. This could be useful for converting Probot website to PWA.
Just a simple JS file along with a few images (.ico files for icons that could be used as splash screen) are needed for it. And it takes very less time to convert it to PWA.
Though, I used it for SPAs so far. I am not sure about it's function for multiple pages.
Checking out now.
https://www.pwabuilder.com/

**Comment by bkeepers** [comment]
I don't think this is worth doing right now. Maybe sometime in the future.
