### ISSUE TITLE
Add new commitlint bot to website

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#163]
Due to #143, it was brought to my attention that there is a new and improved commitlint app being actively maintained here: https://github.com/ahmed-taj/commitlint-bot by @ahmed-taj. 

@ahmed-taj we would love to have your app listed on our site! If you are interested, please feel free to open a PR and add it to the `_apps` folder. More instructions on how to do that in our [Contributing Guidelines](https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md#adding-your-app).

**Comment by hiimbex** [comment]
Lol jk it's already here. https://probot.github.io/apps/commitlint/

**Comment by ahmed-taj** [comment]
☺
