### ISSUE TITLE
Add linter-alex

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#178]
Just discovered https://github.com/swinton/linter-alex!! what a cool app! We'd love to add it to our website if you're interested @swinton!

The steps to do so are here: https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md#adding-your-app

**Comment by swinton** [comment]
Thanks, yeah I'd love to feature it here. I want to make a couple of improvements ([e.g.](https://github.com/swinton/linter-alex/blob/62c6b1d81161215702c4be3c0d5c5baacc07865a/index.js#L35-L36)), but will get a PR opened here this week :bow:
