### ISSUE TITLE
robot & context links in Reference section shows 404 page

### ISSUE THREAD

**Issue by itaditya** [probot/probot.github.io#188]
In the docs, the Reference section of sidebar contains 4 links. The first two i.e. `robot` and `context` on clicking show 404 page.

Check this screenshot

![image](https://user-images.githubusercontent.com/15871340/40883999-d3917412-6727-11e8-8ecd-2f87606b68c6.png)

On clicking the `robot` link it takes me to https://probot.github.io/api/latest/Robot.html and it's showing 404

![image](https://user-images.githubusercontent.com/15871340/40884016-1efcc6b8-6728-11e8-831a-8237a8d48068.png)

**Comment by 1andee** [comment]
This ties to commit e047e9dc540fe9deffffe892a7bb6f6b4f7c1ab5. There were a bunch of .html files in the previous /api/ subfolders that seem to have been omitted in [/api/7.0.0-typescript.4](https://github.com/probot/probot.github.io/tree/master/api/7.0.0-typescript.4).

**Comment by hiimbex** [comment]
cc/ @bkeepers @tcbyrd for ts changes. I think this is relatively high priority to get these docs back up.

**Comment by tcbyrd** [comment]
Sorry everyone! There was some weirdness with the move to TS, which isn't published yet. Fixed in 61a55ee0b9f72f391dd069048bbddaf7803173d1 by re-publishing docs for 6.2.0.

**Comment by hiimbex** [comment]
Thanks for taking care of that @tcbyrd! Confirmed the links work for me now.
