### ISSUE TITLE
Add ci-reporter back

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#196]
Reminder issue for @JasonEtco and myself to add it back once it's public again. (not sure if reminders is enabled on this repo)

/remind me to add ci report back in 3 weeks

**Comment by bkeepers** [comment]
/remind @hiimbex to add ci reporter back in 3 weeks

**Comment by JasonEtco** [comment]
☝️ Not yet, still needs more time 😬 

/remind @hiimbex to add ci reporter back in 3 weeks

**Comment by hiimbex** [comment]
@JasonEtco think it would be okay now?

**Comment by JasonEtco** [comment]
Yep lets do it (I'll get a PR going soon, but feel free to jump in and do it if I'm taking too long)
