### ISSUE TITLE
Change in app owner name breaking links

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#201]
It appears as though @ahmed-taj changed their GitHub user-name to @z0al. This is causing builds to break.

@z0al if you could open a PR updating the links in https://github.com/probot/probot.github.io/blob/master/_apps/dep.md and https://github.com/probot/probot.github.io/blob/master/_apps/commitlint.md I would be very appreciative. 

I don't want to change the links for your app without your permission, but if you'd grant me that permission in this issue, I'd gladly make those changes myself.

**Comment by z0al** [comment]
Oh my bad, didn't think of this :) 

> I don't want to change the links for your app without your permission, but if you'd grant me that permission in this issue, I'd gladly make those changes myself

I would appreciate it, thanks

**Comment by z0al** [comment]
Ok, I made the PR @hiimbex 

Sorry for any inconveniences

**Comment by hiimbex** [comment]
Thanks @z0al and no worries!
