### ISSUE TITLE
Missing title margin on app details page.

### ISSUE THREAD

**Issue by tplk** [probot/probot.github.io#206]
Hello, there's no bottom margin on title element which can cause overlaps with app description.
I suggest adding margin to prevent this and also align description with istallations/stars block.

https://probot.github.io/apps/wip/

![image](https://user-images.githubusercontent.com/20531968/42331590-7583bd38-807e-11e8-85c4-1b6ce1c788e1.png)

**Comment by hiimbex** [comment]
Agree with the sentiment for sure, but I can't reproduce this issue on Chrome or Safari. What browser were you using?

**Comment by tplk** [comment]
@hiimbex I was able to reproduce it on Chrome/Opera, Firefox, Edge and IE11. Looks like it can be a Windows related issue.

**Comment by tplk** [comment]
Still relevant on Windows 10 in any browser because Segoe UI is a system font.
Basically, it's because of Segoe UI "g" and varying line height in the divs.
Not sure about the solution, tbh. Also, no one else seemed to support this issue.
