### ISSUE TITLE
Current Build Failures

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#265]
https://close-issue-app.herokuapp.com/ is 404'ing. The close issues app was added by @helloqiu and includes them and @whtsky as authors. Could one of you update here if you plan to bring the app back up on that heroku URL? If not, we will have to remove it from the website. 

I'm arbitrarily saying 72 hours until we remove the listing, but this is probably  something we should document and be very clear about hosting expectations and maintenance for apps.

**Comment by helloqiu** [comment]
Well, this app is served on heroku with a free plan and the log said `Free app running time quota exhausted`. So maybe waiting for the coming next month can fix this? @hiimbex

**Comment by helloqiu** [comment]
It's back online now.
