### ISSUE TITLE
Update deployment instructions to Now 2.0

### ISSUE THREAD

**Issue by tibdex** [probot/probot.github.io#273]
Zeit recently announced [Now 2.0](https://zeit.co/blog/now-2). It's a move from long-running processes to Lambdas. I think it's a great fit for handling GitHub webhooks and thus for Probot. I developed https://github.com/tibdex/probot-serverless-now to make it easy to deploy Probot apps on Now 2.0. Would you be interested in me making a PR to update the deployment page to have it target Now 2.0?

**Comment by mrchief** [comment]
@tibdex Is there a difference between your wrapper and https://probot.github.io/docs/serverless-deployment/#aws-lambda?

**Comment by tibdex** [comment]
https://github.com/tibdex/probot-serverless-now is for Zeit's Now, not for AWS Lambda.

**Comment by mrchief** [comment]
> https://github.com/tibdex/probot-serverless-now is for [Zeit's Now](https://zeit.co/blog/now-2),

You'd think that people would actually pay attention to the name! 😂 

(_In my defense, it was midnight and I was scrambling to see it work. Wasn't paying too much attention._)
