### ISSUE TITLE
syncing stopped working

### ISSUE THREAD

**Issue by zeke** [probot/probot.github.io#292]
@wei pointed out that this repo is no longer automatically syncing docs changes from the probot repo.

Looking at the [commit activity](https://github.com/probot/probot.github.io/commits/master), it appears there was a daily sync that stopped working 18 days ago:

![Screen Shot 2019-06-18 at 11 09 15 AM](https://user-images.githubusercontent.com/2289/59708390-8a7dfa80-91b9-11e9-8eb8-c42024be6ad5.png)

Here's the output from the failing build:

```
===> Committing and pushing changes
[detached HEAD 397bf0f] Sync data
 Author: Brandon Keepers <bkeepers@github.com>
 52 files changed, 126 insertions(+), 125 deletions(-)
remote: You must verify your email address.
remote: See https://github.com/settings/emails.
fatal: unable to access 'https://[secure]@github.com/probot/probot.github.io.git/': The requested URL returned error: 403
```

https://travis-ci.org/probot/probot.github.io/builds/546994859

Anybody know how this is set up?

**Comment by zeke** [comment]
Looks like it's done by this script: https://github.com/probot/probot.github.io/blob/master/script/remote-sync

**Comment by zeke** [comment]
There's a cron job on Travis that runs daily:

![Screen Shot 2019-06-18 at 11 21 21 AM](https://user-images.githubusercontent.com/2289/59709286-41c74100-91bb-11e9-8266-e6b570a0e24f.png)

In `.travis.yml`

```yml
script: "./script/cibuild"
```

In `./script/cibuild`:

```sh
#!/bin/sh

case "$TRAVIS_EVENT_TYPE" in
  cron ) script/remote-sync;;
  *    ) script/test;;
esac
```

**Comment by zeke** [comment]
I'm going to try replacing the `GH_TOKEN` env var in Travis.

**Comment by zeke** [comment]
Ok I create a new PAT with Repo scope and added it. The next cron job is schedule to run in about 5 hours. 🤞

**Comment by zeke** [comment]
So... it worked, but the build is failing:

https://github.com/probot/probot.github.io/commit/73ed8c048007ff2078ccacb504a08a97fa97fef6

https://travis-ci.org/probot/probot.github.io/builds/547469899

It's curious to see that the commit is still attributed to @bkeepers, even though the cron job is now using a token from my account. 🤔

**Comment by wei** [comment]
If it makes you feel any better, it's been failing for a while https://travis-ci.org/probot/probot.github.io/builds  : D

Also,
https://github.com/probot/probot.github.io/blob/f2034e1e6884157a372aa1e4cbf98e9c91f315d3/.travis.yml#L14-L15

**Comment by wei** [comment]
It just means some of the apps are no longer functional and needs to be removed maybe?
