### ISSUE TITLE
Tests failing due to unresolving app hosts

### ISSUE THREAD

**Issue by zeke** [probot/probot.github.io#293]
Tests are currently failing on this project due to these failing host checks:

```
  1) Failure:
lint test::_apps/todo.md#test_0022_host returns 200 [test/lint_test.rb:59]:
Expected 200 response from https://todo-github-app.now.sh/ping.
Expected: "200"
  Actual: "503"

  2) Failure:
lint test::_apps/linter-alex.md#test_0022_host returns 200 [test/lint_test.rb:59]:
Expected 200 response from https://linter-alex.herokuapp.com/ping.
Expected: "200"
  Actual: "503"

  3) Failure:
lint test::_apps/issuelabeler.md#test_0022_host returns 200 [test/lint_test.rb:59]:
Expected 200 response from https://1th3h69bkc.execute-api.ap-southeast-1.amazonaws.com/production/ping.
Expected: "200"
  Actual: "504"
```

👋 @JasonEtco, @swinton, and @riyadhalnur: you appear to be the owners of these three apps, respectively. Are these apps still maintained, or should we disable them and/or remove from the site?

**Comment by riyadhalnur** [comment]
Mine is still maintained. Thanks for bringing this up. I'll debug the issue on my side.

**Comment by riyadhalnur** [comment]
I've fixed the bot but due to issues on upstream module, I'm not able to update the host for `issuelabeler`. I opened an issue for this already on repo - https://github.com/probot/serverless-lambda/issues/24

**Comment by zeke** [comment]
Thanks for the update @riyadhalnur. What do you think about removing the app until the hosting issue is resolved?

**Comment by riyadhalnur** [comment]
@zeke I updated the listing to point to the new host. `/ping` will work but the `/stats/` won't. PR here https://github.com/probot/probot.github.io/pull/299

**Comment by zeke** [comment]
todo app URL was updated here: https://github.com/probot/probot.github.io/pull/291
