### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#3]
https://probot.github.io/docs/ should include all the docs for building new probot plugins.

To figure out:

- Where do the docs live? Currently they're in the [docs directory on probot/probot](https://github.com/probot/probot/tree/master/docs). Should they stay there and get copied to the site on release? Or should they live in this repo?
- Move publishing of API docs from `gh-pages` branch of probot/probot repo into this repo (cc https://github.com/probot/probot/issues/133 https://github.com/probot/probot/pull/105)

**Comment by kytrinyx** [comment]
Or secret door number 3: a `docs` repo. This could be pinned on the `probot` org, which helps make it discoverable.
