### ISSUE TITLE
feature request: better app handling

### ISSUE THREAD

**Issue by cyberhck** [probot/probot.github.io#302]
On travis-ci, we test if {url}/ping returns something with status 200.

I think it'd be really awesome if we can create an issue on that repo with a good issue report, as soon as the app doesn't return 200.

If an open issue already exists for more than 3 days, we can ignore that repo for 30 days and finally remove it from this repo.

Thoughts?

**Comment by gr2m** [comment]
Sounds like a fun little bot idea 👍
