### ISSUE TITLE
Automate updates of docs/ submodule

### ISSUE THREAD

**Issue by gr2m** [probot/probot.github.io#321]
This is a follow up of https://github.com/probot/probot.github.io/pull/318.

I think I would run an action in the probot/probot repository which updates probot.github.io whenever there is a change in the docs/ folder. 

@BinaryMuse do you know if this can be done with an API call (such as https://developer.github.com/v3/repos/contents/#create-or-update-a-file) or only with an git operation?

**Comment by BinaryMuse** [comment]
> @BinaryMuse do you know if this can be done with an API call

I believe this is possible but it takes a little finagling (you have to manually [create a tree](https://developer.github.com/v3/git/trees/#create-a-tree) then use that tree to make a commit), but [actions/checkout](https://github.com/actions/checkout) should also make this possible via command line scripting.

**Comment by MaximDevoir** [comment]
This would be great. I'll work on a workflow for [Probot](https://github.com/probot/probot) that will:

1. Run when a change to the [`/docs`](https://github.com/probot/probot/tree/master/docs) docs folder is pushed into master.
1. Use [actions/checkout](https://github.com/actions/checkout) to checkout [multiple repositories](https://github.com/actions/checkout/blob/c85684db76ba6ef08713c10cf4befe3318887415/README.md#checkout-multiple-repos-side-by-side) (both Probot and probot.github.io - and maybe we don't even need to checkout the Probot repo in this step).
1. Update the [Probot submodule](https://github.com/probot/probot.github.io/tree/master/_submodules) to the latest commit from the Probot repo.
1. Push the changes in probot.github.io to the repo (this may require a PAT); initiating a `publish` script.



And wow, as I was writing this I remembered why I opened probot/probot#1089.

The Probot repo already has a script that does all the things mentioned above. See Probot's [`publish-docs`](https://github.com/probot/probot/blob/master/script/publish-docs) script. I can't pinpoint when this occurred, but the script to run `publish-docs` has been removed and not added to the [`.travis.yml`](https://github.com/probot/probot/blob/9265609c91f4b76282c281bdef787d684cf2c5bf/.travis.yml) file.

I'll work on adding a `update-docs` stage to [`.travis.yml`](https://github.com/probot/probot/blob/9265609c91f4b76282c281bdef787d684cf2c5bf/.travis.yml) that runs the `publish-docs` script after the `release` stage is successfully completed while on the `master` branch.
