### ISSUE TITLE
App directory no longer updated

### ISSUE THREAD

**Issue by robvanderleek** [probot/probot.github.io#332]
Hi,

The app directory at https://probot.github.io/apps/ has not been updated for a while. 
Looking at https://github.com/probot/probot.github.io/tree/master/_apps I see that the [sync-data](https://github.com/probot/probot.github.io/blob/master/script/sync-data) script did not ran in the last ~2 weeks. Is there an issue with the Travis CI cron job?

**Comment by gr2m** [comment]
Hmmm ... looks like the cron job is running, but failing. We need to address some errors in there:
https://travis-ci.org/probot/probot.github.io/builds/641167335

Could you start a PR addressing the problems?

**Comment by robvanderleek** [comment]
Hey @gr2m 

I looked into the Travis CI cron job but as far as I can see all errors in this job are generated by misconfigurations  (mostly dead links) of registered Probot apps.

For example, the `sync-data` step contains errors like:
```
Syncing pr-triage/app
404 Not Found
Syncing wip/app
404 Not Found
Syncing kentaro-m/auto-assign
404 Not Found
Syncing svanboxel/delete-merged-branch
503 Service Unavailable
Syncing fossapps/pr_label_enforcer
308 Permanent Redirect
```
And the `html-proofer` step contains errors like:
```
- _site/apps/close-issue/index.html
  *  External link https://codecov.io/gh/offu/close-issue-app/branch/master/graph/badge.svg failed: got a time out (response code 0)
- _site/apps/commitlint/index.html
  *  External link https://github.com/yhlben failed: 404 No error
  *  External link https://github.com/yhlben.png failed: 404 No error
```
I guess fixing these issues means chasing the app maintainers to update their configurations.
Perhaps a more sustainable solution would be to remove misconfigured apps and notify app maintainers automatically, so they can fix it themselves. But that would require a fairly extensive rewrite.

**Comment by gr2m** [comment]
Or we configure the CI not to fail to update the app gallery, but create issues. 

It's becoming quite a big maintainers overhead, and we are very low on maintainers right now. If you could help in anyway, that would be much appreciated

**Comment by robvanderleek** [comment]
The build is running again, I'm closing this issue.
