### ISSUE TITLE
Mention that event forwarding is disabled by default

### ISSUE THREAD

**Issue by lpellegr** [probot/probot.github.io#334]
Creating a Github app with _probot_ for the first time, I struggled a lot trying to understand why the default app scaffolded with _npx_ was not receiving events. 

After some time, I noticed that Github apps have an "Active" option that is disabled by default:

![Screenshot from 2020-02-17 14-25-43](https://user-images.githubusercontent.com/128898/74657922-87e10400-5191-11ea-82ab-cc3c15d83313.png)

Once the option has been enabled, the default app sample is working appropriately.

It would be helpful to discuss or mention the option in the Getting Started part of the documentation.

**Comment by gr2m** [comment]
I think this is a feature that was recently added by GitHub. Ideally we would set the checkbox to enabled by default. Someone would need to look into it though. I assume you used the setup wizzard that you see when you start your probot app for the first time?

**Comment by lpellegr** [comment]
Yes.

**Comment by gr2m** [comment]
I think the checkbox is now enabled by default
