### ISSUE TITLE
API for smee.io ?

### ISSUE THREAD

**Issue by matjung** [probot/probot.github.io#338]
Hello,
A link in github pointed to smee which pointed to probot team.
https://developer.github.com/apps/quickstart-guides/setting-up-your-development-environment/

Is smee.io is having an API?

Is it possible to find out what token github posted to smee without installing additional code to my local engineering environment?

**Comment by gr2m** [comment]
Do you mean you would like to retrieve the webhook payload that GitHub posted to smee.io? 

That should be possible using EventSource in the browser. There is a package for NPM: https://github.com/EventSource/eventsource
