### ISSUE TITLE
add favicon files

### ISSUE THREAD

**Issue by Jme7** [probot/probot.github.io#340]
In order to enable your icon to be visible on a lot more platforms, I would recommend a favicon generator (I like [this one](https://realfavicongenerator.net/)) to create the favicons.

**Comment by gr2m** [comment]
Happy to accept a pull request with more Favicon formats, in higher resolutions

**Comment by Jme7** [comment]
ok, I can do that, and I will have some code for you to put in each webpage (you don't need this code, unless the device doesn't automatically add the favicon)

@gr2m  Close this issue when you have read this
