### ISSUE TITLE
Installation count no longer updated

### ISSUE THREAD

**Issue by robvanderleek** [probot/probot.github.io#353]
The App installation count on https://probot.github.io/ is no longer updated.

I guess this is related to the performance problems with App `/probot/stats` endpoints. In Probot v10 this [endpoint is even removed](https://github.com/probot/probot/issues/1267).

What is the way forward for App maintainers to get the count updated again? Do they need to provide a `/probot/stats` endpoint that is performant as explained in [issue 1267](https://github.com/probot/probot/issues/1267)?

**Comment by gr2m** [comment]
I created an action that you can run on a schedule: https://github.com/gr2m/app-stats-action

Maybe we can ask the maintainers to run that action? Or create an action in the probot organization that you could run, and whenever you run the action, we check if the app is listed in our gallery. If it is, we could update the installation count?

**Comment by robvanderleek** [comment]
Hi @gr2m 

Based on your GitHub Action I've added a [scheduled Action workflow](https://github.com/robvanderleek/create-issue-branch/blob/1882d4d949e5040c85c458ff0f82653cb06a40fb/.github/workflows/app-stats.yml) to my repo. That workflow pushes a `stats.json` to the repo which is [served](https://github.com/robvanderleek/create-issue-branch/blob/1882d4d949e5040c85c458ff0f82653cb06a40fb/src/probot.js#L23) from my `probot.js` file.

The installation count on https://probot.github.io/apps/ for my App is now updated again, thanks! 👍 

Although this is not too complicated for App maintainers to implement, it's not very elegant.
It would be nice if GitHub could provide this information about Apps through their API, that would make things a lot easier for the probot site. Anyway, this solves the issue for me.

**Comment by gr2m** [comment]
>  That workflow pushes a `stats.json` to the repo which is [served](https://github.com/robvanderleek/create-issue-branch/blob/1882d4d949e5040c85c458ff0f82653cb06a40fb/src/probot.js#L23) from my `probot.js` file.

fabulous hack!

**Comment by gr2m** [comment]
> It would be nice if GitHub could provide this information about Apps through their API

Hawman I've been asking for ... a long time. Maybe shoot a message to https://support.github.com/contact so the priority might get bumped. I'd really appreciate it.

**Comment by robvanderleek** [comment]
FWIW I've reached out to GH Support about this.
