### ISSUE TITLE
Grave accents (`) in headings break anchor links

### ISSUE THREAD

**Issue by froi** [probot/probot.github.io#365]
Hey there 👋🏼 

I was reading the Probot docs and noticed that some anchor links are broken. The links that I noticed are found in the _development_ page, specifically:

- Use run
- Use server
- Use createNodeMiddleware
- Use probot

It seem the the headings have a __\`__ around run, server, createNodeMiddleware and probot. It's causing the anchor links to be generated as _#use-codecreatenodemiddlewarecode_ (see bellow). 

![image](https://user-images.githubusercontent.com/1918027/112068687-d5703300-8b40-11eb-9f2d-bc7abe1017f3.png)

The regular links do not have the __code__ prefix or suffix

![image](https://user-images.githubusercontent.com/1918027/112069487-495f0b00-8b42-11eb-94c7-96fd03c4e0b2.png)

This seems to only happen when rendering the site and not when previewing the markdown files. Are the __\`__ necessary? Are they part of some automation? Should I submit a PR to the [probot/probot](https://github.com/probot/probot) repo to remove the __\`__?

I'll be happy to submit a PR. Thanks.

**Comment by gr2m** [comment]
> Should I submit a PR to the [probot/probot](https://github.com/probot/probot) repo to remove the **`**?

yes please, that'd be great!

**Comment by froi** [comment]
@gr2m Hello there 👋🏼 

I think this change as merged into [probot/probot](https://github.com/probot/probot) some time ago. I'm closing it out 😄
