### ISSUE TITLE
Daily scheduled TravisCI build no longer runs

### ISSUE THREAD

**Issue by robvanderleek** [probot/probot.github.io#369]
The daily scheduled [CI build](https://github.com/probot/probot.github.io/blob/981d05f59f6a256d9c8d71c383b222d78e10f8ca/.travis.yml) in [TravisCI](https://travis-ci.org/github/probot/probot.github.io/branches) no longer runs since building on travis-ci.org is ceased.

![image](https://user-images.githubusercontent.com/5324924/123901190-d0eebe00-d96a-11eb-9ff8-ed490d0c7b94.png)

**Comment by gr2m** [comment]
if anyone would you like to replace the travis setup with GitHub Actions that'd be great

**Comment by robvanderleek** [comment]
I tried a straightforward migration from TravisCI to GH Actions in this PR: https://github.com/probot/probot.github.io/pull/370

My Ruby experience is little to none, the actual builds still fail and I'm not sure if I can test cron scheduled jobs in a fork but I guess we need to start somewhere. Can you take a look @gr2m ?

**Comment by gr2m** [comment]
done via https://github.com/probot/probot.github.io/pull/370. The tests are failing and I see 308 responses in there? I don't even know what that means 🤷🏼

**Comment by robvanderleek** [comment]
The 308s (had to look it up too of course) are caused by a permanent redirect from the `now.sh` domain URLs to the `vercel.app` domain.
I've replaced `now.sh` with `vercel.app` in [this draft PR](https://github.com/probot/probot.github.io/pull/371). Unfortunately a large amount of the Apps that failed with 308 now fail with 404, I guess because they are permanently down.

Any advice how to proceed?

**Comment by gr2m** [comment]
> I guess because they are permanently down

If I recall correctly, lots of the apps have not been working before, or they have been moved to a serverless environment without implementing the `GET ping` route. At some point it would be good to triage all the apps, but I think we should wait for @AaronDewes's pull request #367

**Comment by robvanderleek** [comment]
Lots of the Apps that fail the ping check also give a 404 on the root URL. Makes sense to do a cleanup after #367 is merged :+1:

A thing that still bothers me: I can't figure out why the [daily scheduled workflow](https://github.com/probot/probot.github.io/blob/0beea7e8e1fc2470cc5ed99ba3465d1487a7b532/.github/workflows/daily-sync.yml) isn't running. I use a [similar scheduled workflow](https://github.com/robvanderleek/create-issue-branch/blob/2b2f09916af4ec40f0d33494d21cb3d9055c10ad/.github/workflows/app-stats.yml) in my own App repo. Does something perhaps needs to be enabled in the Actions part of the repo settings for the scheduled workflow to run?

**Comment by gr2m** [comment]
it is running from what I can see?
https://github.com/probot/probot.github.io/actions/runs/992808934

Or am I missing something?

**Comment by AaronDewes** [comment]
Fixed by https://github.com/probot/probot.github.io/pull/367 and https://github.com/probot/probot.github.io/pull/370, so I guess this can be closed .

**Comment by robvanderleek** [comment]
Nice, the numbers for my app are up-to-data again, also hello dark mode.

The ordering on the landing page used to be based on number of installations, now it appears to be reversed alphabetically.
Not sure how the ordering should be though.

**Comment by AaronDewes** [comment]
I guess I'll have to fix that too, sorry about that

**Comment by robvanderleek** [comment]
Hi @AaronDewes 

Thanks! New design looks great!

Rob
