### ISSUE TITLE
Link at the bottom of `/docs/configuration` to edit the documentation also does not work.

### ISSUE THREAD

**Issue by gr2m** [probot/probot.github.io#373]
the link at the bottom of https://probot.github.io/docs/configuration/ to edit the documentation also does not work.

via https://github.com/probot/probot/pull/1567

**Comment by gr2m** [comment]
ping @AaronDewes ☝️

**Comment by AaronDewes** [comment]
> ping @AaronDewes :point_up:

Sorry, I'll debug this, and create a fix PR tomorrow
