### ISSUE TITLE
Bug with new apps

### ISSUE THREAD

**Issue by AaronDewes** [probot/probot.github.io#383]
When a new app is posted to this repo,  the author doesn't add the amount of stars. When app data is synced, it gets added.
The problem is that a GitHub actions push can't trigger another GitHub action.

There are two ways to resolve this:

1. Push an empty commit after an app gets updated.
2. Build & update the website during the app update workflow.
I prefer 2 because it's automated and also works when other data gets updated.

@gr2m What do you prefer?

**Comment by gr2m** [comment]
>  The problem is that a GitHub actions push can't trigger another GitHub action.

It can, we just need to use a different means of authentication that a `secrets.GITHUB_TOKEN`. This PR should make it work: https://github.com/probot/probot.github.io/pull/384

**Comment by gr2m** [comment]
Can you give it a try if it works as expected?

**Comment by AaronDewes** [comment]
It seems like the commit author needs to be set to probotbot too.

**Comment by gr2m** [comment]
it looks like that is not possible, the usage of `GITHUB_ACTOR` is hardcoded:
https://github.com/davidolrik/push/blob/b88b2c57f3a4c23bf2abf091c319e77088dd0172/start.sh#L38

`GITHUB_ACTOR` will always be set to GitHub Actions. Let me replace that step with simple `git` commands instead
