### ISSUE TITLE
Add /contribute page

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#39]
The "Contribute" link currently just links to the probot/probot repository, but I think it'd be nice to replace it with a custom page that includes:

- Welcome/invitation to contribute
- Link to join Slack channel
- Link to [app ideas](https://github.com/probot/plugin-template/issues)
- Link to starter issues

**Comment by hiimbex** [comment]
💖 this! I think it would be great to start making use of labels to get new people involved such as [first timers only](https://twitter.com/first_tmrs_only) or good for beginners, idk the exact conventions for these kinds of labels, but it would be cool to draw from all issues that have relevant labels and use that to generate the site.

**Comment by JasonEtco** [comment]
Closed by #51
