### ISSUE TITLE
https://probot.github.io/api/ pages 404'ing

### ISSUE THREAD

**Issue by metasean** [probot/probot.github.io#390]
The [Probot "Reference" side nav](https://probot.github.io/docs/) links that should go to `api/latest` pages currently result in a 404 page.  This includes [Probot](https://probot.github.io/api/latest/classes/probot.html), [context](https://probot.github.io/api/latest/classes/context.html), [run](https://probot.github.io/api/latest/index.html#run), and [createNodeMiddleware](https://probot.github.io/api/latest/index.html#createnodemiddleware) links.

|  Link section in question    |  [Probot](https://probot.github.io/api/latest/classes/probot.html), [context](https://probot.github.io/api/latest/classes/context.html), [run](https://probot.github.io/api/latest/index.html#run), & [createNodeMiddleware](https://probot.github.io/api/latest/index.html#createnodemiddleware) links<br />just lead to this sad Probot |
| --- | --- |
| <kbd><img width="150" alt="" src="https://user-images.githubusercontent.com/7552754/155244260-849317d0-a5c4-4053-be30-cb7cb1614961.png"></kbd> | <kbd><img width="500" alt="" src="https://user-images.githubusercontent.com/7552754/155244028-31b06bc1-7396-4b23-a7b1-de52696f6669.png"></kbd> |

The [probot.github.io/blob/master/api/latest](https://github.com/probot/probot.github.io/blob/master/api/latest) directory appears to be [correctly symlinked](https://github.com/probot/probot.github.io/commits/master/api/latest) to the latest version, assuming there hasn't been some other repo change that would consume the symlink differently than it has been for a while.

The [probot.github.io/tree/master/api/12.2.1/classes](https://github.com/probot/probot.github.io/tree/master/api/12.2.1/classes) directory appears comparable to the [12.2.0/classes](https://github.com/probot/probot.github.io/tree/master/api/12.2.0/classes) directory (of course that comparison assumes the api pages were generated and deployed as expected with the 12.2.0 docs [1]).

Hopefully, someone who knows this repo and documentation process, better than I, can figure out why the api directory is 404ing.

[1]: Sadly, the only snapshot is from [way back in 2020](https://web.archive.org/web/20201216204716/https://probot.github.io/api/latest/classes/probot.html).

**Comment by AaronDewes** [comment]
It seems like we updated typedoc recently, which changed the way these names were generated. Thank you for reporting this, I'll fix it soon.
