### ISSUE TITLE
Post installation page for apps

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#4]
A lot of apps have steps that need to be taken after installation. For example, the [stale](https://github.com/probot/stale#usage) plugin requires a `.config/stale.yml`, and the [DCO](https://github.com/probot/dco) plugin optionally suggests [required statuses](https://github.com/probot/dco/blob/master/docs/required-statuses.md).

It might be nice if all of the listed apps had a post-install page (e.g. `https://probot.github.io/apps/stale/install`) with info on what to do after installing the app.

**Comment by knrt10** [comment]
Let me try and implement this.
