### ISSUE TITLE
Stars count is not regularly updated on probot `apps` URL.

### ISSUE THREAD

**Issue by tenshiAMD** [probot/probot.github.io#414]
I noticed that the stars count is not regularly updated on the `apps` URL (https://probot.github.io/apps/).

**Comment by gr2m** [comment]
Looks like our app sync workflow is failing:
https://github.com/probot/probot.github.io/actions/workflows/sync.yml

The error is rather cryptic, if anyone would like to dig into it, that'd be great

**Comment by tenshiAMD** [comment]
@gr2m sure I can take a look at this later. Thanks! 🎉

**Comment by tenshiAMD** [comment]
>I tried to ignore the .netlify directory and it works.
It seems like an issue between Netlify & eleventy.

@gr2m they suggest trying this if we can fix the issue

Reference:
- https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues/18

**Comment by gr2m** [comment]
Looks like it was a problem with the markdown, replacing

````
```sh
````

with
 
````
```shell
````

did the trick. But I added `.netlify` for good measure, won't hurt. Thank you for looking into it 👍🏼

**Comment by tenshiAMD** [comment]
@gr2m hmm looks like the stars count is still not being updated at all

**Comment by gr2m** [comment]
hmm must be a different problem now

**Comment by gr2m** [comment]
The update was pushed to the `gh-pages` branch:
https://github.com/probot/probot.github.io/commit/f3b423a2167913424ad91999c2d5e21b02c84879

The problem might be related to today's outages? https://www.githubstatus.com/

Which app's star count is currently out of sync?

**Comment by tenshiAMD** [comment]
@gr2m looks like all is updated now. Closing this now. Thanks! 🎉
