### ISSUE TITLE
Social card and SEO

### ISSUE THREAD

**Issue by JasonEtco** [probot/probot.github.io#49]
Our wonderful website could use a social card and some better/more descriptive SEO tags. I'll open up a PR soon, will likely use the [`jekyll-seo-tag`](https://github.com/jekyll/jekyll-seo-tag) plugin to facilitate some of the work, and I'll put together a simple social card with our 🤖 persona.

Mostly opening this issue so that I don't forget to do it, but if you have any thoughts feel free to share!

**Comment by anglinb** [comment]
@JasonEtco Yay--should def add this 🎉🎉🎉  Is `jekyll-seo-tag` on the whitelist for pages?

**Comment by JasonEtco** [comment]
> Is jekyll-seo-tag on the whitelist for pages?

It is indeed 👍

**Comment by JasonEtco** [comment]
Some quick options, let me know what y'all (@probot/maintainers and anyone else) think:

![image](https://user-images.githubusercontent.com/10660468/30409033-824ffffe-98d0-11e7-8d6f-322400b2b9ef.png)

Generally speaking, light social cards are less impactful than dark ones so I threw in the blue background options even though it's a little off-brand.

**Comment by hiimbex** [comment]
Wow, thanks so much for doing this @JasonEtco! Love these! I'm personally a fan of the second row, first and second column ones, white/off-white with Probot as the casing. I think they're the most "on brand."

Maybe the blue ones could work with a paler blue? or a darker gray, but I'm not too concerned about the impact of social cards when we're still pretty small/not advertising to a huge audience.
