### ISSUE TITLE
Sync production data

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#5]
The current website includes number of stars & installs, as well as a list of organizations/users that have the app installed. These will need to be synced regularly via a script.

Stars will be easy to get from the API.  Number of installs, and popular installs, may only be available via an authenticated API request from the installation itself. One crazy idea is to build in a `/stats` endopoint into probot itself that will return this data so every deployed probot plugin makes it available.

**Comment by kytrinyx** [comment]
> One crazy idea is to build in a /stats endopoint into probot itself that will return this data so every deployed probot plugin makes it available.

That is a most excellent idea!

If people complain that they don't want this available it could be made configurable (default: on) with fairly little effort, it seems.

**Comment by hiimbex** [comment]
@bkeepers out of curiosity, how _do_ you find out what organizations have your app installed?

**Comment by bkeepers** [comment]
> @bkeepers out of curiosity, how _do_ you find out what organizations have your app installed?

Hopefully this will be built into Probot: https://github.com/probot/probot/pull/181/files#diff-1263abd83b0a22d4c37c488666678740R26

**Comment by bkeepers** [comment]
Fixed by #43 and #44
