### ISSUE TITLE
Make office hours warning less jarring

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#54]
<img width="1916" alt="screen shot 2017-09-22 at 4 38 25 pm" src="https://user-images.githubusercontent.com/13410355/30749708-8185ad36-9fb4-11e7-8544-15b1338d6e2e.png">

The red makes me think there's an error or something broken, it's a little off putting.

cc/ @JasonEtco for design :hammer_and_wrench:

**Comment by JasonEtco** [comment]
Agreed; red is aggressive. Blue would be nice 👍 I can make a PR when I get a chance.

Also I would change it to end in a `!`, its slightly more inviting.
