### ISSUE TITLE
Text color became unreadable

### ISSUE THREAD

**Issue by Varun-Kolanu** [probot/probot.github.io#582]
How the text in probot.github.io became black and unreadable suddenly?

![image](https://github.com/probot/probot.github.io/assets/112728411/29b96090-23cb-4303-888b-d3222722310e)

Settings:
1. Asus Vivobook S15
2. Chrome
3. Dark Mode

**Comment by AaronDewes** [comment]
Thanks for the notice, this is broken in every browser. I'm fixing it.

**Comment by AaronDewes** [comment]
This has been fixed by https://github.com/probot/probot.github.io/commit/79569ff2f1962c5d703ce680aff31e64273c99bf. Make sure to clear your browser cache if you are still experiencing issues.
