### ISSUE TITLE
chore: Sync data stopped 

### ISSUE THREAD

**Issue by Varun-Kolanu** [probot/probot.github.io#587]
- The commit `chore: Sync data` from the `probotbot` was continuous daily. But it stopped after 26th June and the Stars in the repo etc didn't get update since then.
- Was the bot discontinued or something?

![image](https://github.com/probot/probot.github.io/assets/112728411/ef407a94-59e2-415e-b955-7b6241b5fcc2)

**Comment by Varun-Kolanu** [comment]
@AaronDewes Is this any bug or was it intentionally closed?

**Comment by Varun-Kolanu** [comment]
@AaronDewes Anyone there?

**Comment by AaronDewes** [comment]
This was a bug I thought I fixed but didn't. I'll reopen it, thanks for noticing!

**Comment by wolfy1339** [comment]
This is caused by a known issue with ts-node, https://github.com/TypeStrong/ts-node/issues/2100

**Comment by Varun-Kolanu** [comment]
> This is caused by a known issue with ts-node, [TypeStrong/ts-node#2100](https://github.com/TypeStrong/ts-node/issues/2100)

Was the ts-node issue solved or is it unsolved till now?

**Comment by wolfy1339** [comment]
There are workarounds that we can use, but the underlying issue is still present

**Comment by wolfy1339** [comment]
The sync data workflow should now be working
