### ISSUE TITLE
Document criteria & process for listing new apps

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#6]
The 6 apps listed now were hand-picked by me. Going forward, we need to outline the criteria and process for listing an app.

What should the criteria be?

**Comment by kytrinyx** [comment]
something something [best practices](https://github.com/probot/probot/blob/master/docs/best-practices.md)?

**Comment by hiimbex** [comment]
Just writing down some thoughts from earlier today:

Probot is a relatively small community and currently the majority of plugins are created by people who are also probot maintainers. So it's easy to host currently. As probot could potentially expand, new plugins need to be hosted.

We talked about only hosting them once they had a certain number of stars. _But_ how can anyone gain a following without a hosted app? So, this is sort of a chicken and an egg problem. 

Therefore, I propose that in the near future we host all apps that:
- actually work (ie they run without errors and perform some sort of action on GitHub through the API)
- do something not already done by an existing probot plugin
- have minimal tests
- have minimal documentation
- are open source 
- have a license
- have someone willing to at least minimally maintain them for the near future

Thoughts?

**Comment by bkeepers** [comment]
That sounds like a great start to me.

> We talked about only hosting them once they had a certain number of stars. But how can anyone gain a following without a hosted app? So, this is sort of a chicken and an egg problem.

I know this creates a chicken/egg problem, but if the website also included a list of plugins that didn't have hosted installs, it might help give them some exposure.

We can see how it goes and adjust the criteria as requests start coming in. I just don't want to get to the point where we hosting hundreds of apps and having to deal with operations issues.
