### ISSUE TITLE
Add to Calendar isn't working

### ISSUE THREAD

**Issue by clarkbw** [probot/probot.github.io#61]
The Add to Calendar button isn't working for me.

<img width="482" alt="screen shot 2017-09-26 at 7 35 30 am" src="https://user-images.githubusercontent.com/2134/30866159-552f10fc-a28d-11e7-9124-79f36fe00bbb.png">

I end up at this error page.  I've tried iCal and Google, haven't tested the others yet.

`AddToCalendar.com gets invalid event parameters`

https://addtocalendar.com/atc/ical?utz=-420&uln=en-US&vjs=1.5&e[0][date_start]=2017-09-29T10%3A00%3A00-07%3A00&e[0][date_end]=2017-09-29T11%3A00%3A00-07%3A00&e[0][title]=Probot%20Office%20Hours&e[0][description]=Join%20us%20every%20Friday%20to%20give%20feedback%2C%20ask%20questions%2C%20get%20help%2C%20or%20just%20chat%20about%20ideas.&e[0][location]=https%3A%2F%2Fgithub.zoom.us%2Fj%2F221410810

**Comment by bkeepers** [comment]
Thanks @clarkbw, it should be fixed now.
