### ISSUE TITLE
Improve footer layout on mobile

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#64]
The footer on the mobile layouts needs a little love. The buttons are getting a little to fresh with that email signup form. I'm open to ideas for how to improve it.

If you're looking for recommendations, I would consider adding a margin on the bottom of the email form.

<img width="308" alt="featured_apps___probot" src="https://user-images.githubusercontent.com/173/30940992-f6281bea-a3a8-11e7-9c7b-205e6ff7c434.png">

## How

The website uses [primer](http://primercss.io), which is GitHub's 😻 CSS toolkit. It's amazing, but docs are currently being revamped, and thus not entirely up to date.

For adding margin to the bottom of an element, try adding the `mb-2` CSS class to the element. You can also experiment with `mb-1`, `mb-6`, or anywhere inbetween. If you only want the margin on mobile, you can use `mb-sm-2`.

```html
<div class="mb-2">This div will have a little margin on the bottom.</div>
```

Feel free to ask questions about primer here or on [Slack](https://probot-slackin.herokuapp.com/)

**Comment by Gutem** [comment]
I do it
