### ISSUE TITLE
Syncing stars/updated broken

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#70]
It looks like [this commit](https://github.com/probot/probot.github.io/commit/b17ed4f1db7b48803f74827ad30dbdacf5c5ecd1) failed due to rate limiting  2 days ago, and the sync hasn't been run since even though it should have run yesterday.

cc/ @JasonEtco @bkeepers

**Comment by JasonEtco** [comment]
My poor [`todo`](https://todo.jasonet.co) listing doesn't have any stars on the website 😭

It is entitled to its meager 2 stars.
