### ISSUE TITLE
Change Build to Docs

### ISSUE THREAD

**Issue by JasonEtco** [probot/probot.github.io#76]
Based on the discussion happening in https://github.com/probot/probot/pull/295, I'd like to open this issue to decide if we should change the navigation to read **Docs** or **Documentation** instead of **Build**. This makes it clearer to visitors where to find information about building with Probot. If anyone else has any ideas on how to make the documentation more visible (especially the API docs for `context` and `robot`), I'd love to hear 'em!

**Comment by jarrodldavis** [comment]
Maybe another nav link could be added to go directly to the API reference documentation?
