### ISSUE TITLE
Homepage SVG 404s

### ISSUE THREAD

**Issue by JasonEtco** [probot/probot.github.io#79]
https://github.com/probot/probot.github.io/blob/91093bd010787f35c7ec0e3a30c98b881197acac/index.html#L65

It looks like this SVG image no longer exists on GitHub's CDN. We can of course host it locally, but only if we can find it again.

I'm currently on a 🚋 so the very slow [Archive.org](http://archive.org) will be even slower; this is a link to [the SVG we need to find](https://assets-cdn.github.com/images/modules/site/home-illo-conversation.svg).

**Comment by bkeepers** [comment]
Works on my machine.

**Comment by JasonEtco** [comment]
Must be cached for you @bkeepers, see URL in address bar:

![image](https://user-images.githubusercontent.com/10660468/31773973-6291a7e6-b4b2-11e7-9dad-d9bdadb36206.png)
